python main.py
services:
  - type: web
    name: stripe-shopify-integration
    env: python
    region: oregon  # or choose your preferred region
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    branch: main
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production
      - key: STRIPE_SECRET_KEY
        fromEnvVar: STRIPE_SECRET_KEY
      - key: SHOPIFY_API_KEY
        fromEnvVar: SHOPIFY_API_KEY
      - key: SHOPIFY_API_SECRET
        fromEnvVar: SHOPIFY_API_SECRET
      - key: SHOPIFY_ADMIN_TOKEN
        fromEnvVar: SHOPIFY_ADMIN_TOKEN
